// Purpose: Exercise real PDF.js mixed-page detection/rendering with a controlled local OCR boundary.
// Inputs: The synthetic PDF generated by the native PDFKit/Vision regression harness.
// Outputs: Assertions for raster body inclusion, retained headers, warnings, page mapping and OCR caps.
// Side effects: Reads a fictional fixture and renders local canvases; no network or live OCR services.
import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { createCanvas } from '@napi-rs/canvas';

// MARK: - Real PDF parsing with a controlled recognition boundary
const state = vi.hoisted(() => ({
  pages: 0,
  failOCR: false,
  failInspection: false,
  recognize: vi.fn(),
  terminate: vi.fn(),
}));
vi.mock('pdfjs-dist', async () => {
  const actual = await import('pdfjs-dist/legacy/build/pdf.mjs');
  const require = createRequire(import.meta.url);
  actual.GlobalWorkerOptions.workerSrc = require.resolve('pdfjs-dist/legacy/build/pdf.worker.mjs');
  return {
    OPS: actual.OPS,
    GlobalWorkerOptions: {},
    getDocument(options: Parameters<typeof actual.getDocument>[0]) {
      const task = actual.getDocument({ ...(options as object), disableFontFace: true });
      return {
        destroy: () => task.destroy(),
        promise: task.promise.then((pdf) => ({
          numPages: state.pages || pdf.numPages,
          getPage: async (number: number) => {
            const page = await pdf.getPage(state.pages ? 1 : number);
            if (state.failInspection && number === 1)
              page.getOperatorList = async () => {
                throw new Error('Synthetic inspection failure');
              };
            return page;
          },
        })),
      };
    },
  };
});
vi.mock('tesseract.js', () => ({
  createWorker: async () => ({ recognize: state.recognize, terminate: state.terminate }),
}));
import { extractDocument } from './extractDocument';

beforeEach(() => {
  state.pages = 0;
  state.failOCR = false;
  state.failInspection = false;
  state.recognize.mockReset().mockImplementation(async (canvas: ReturnType<typeof createCanvas>) => {
    expect(canvas.width).toBeGreaterThan(600);
    expect(canvas.height).toBeGreaterThan(700);
    // PDF.js really rendered the original; OCR is the only controlled boundary.
    const pixels = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data;
    expect(pixels.some((value, index) => index % 4 === 0 && value < 100)).toBe(true);
    if (state.failOCR) throw new Error('Synthetic OCR failure');
    return {
      data: { confidence: 99, text: 'Dose: 100 mg\nNo fracture seen\nFictional OCR regression only' },
    };
  });
  state.terminate.mockReset().mockResolvedValue(undefined);
  vi.stubGlobal('window', {
    setTimeout,
    clearTimeout,
    requestAnimationFrame: (callback: () => void) => setTimeout(callback, 0),
    cancelAnimationFrame: clearTimeout,
  });
  vi.stubGlobal('location', { origin: 'http://localhost' });
  vi.stubGlobal('document', { createElement: () => createCanvas(1, 1) });
});
afterEach(() => vi.unstubAllGlobals());
async function mixedPDF() {
  const bytes = await readFile(
    new URL('../../../../../Tests/DocumentImportChecks/mixed-content.pdf', import.meta.url),
  );
  return new File([bytes], 'mixed-content.pdf', { type: 'application/pdf' });
}
// MARK: - Mixed source success, recognition failure and resource bounds
describe('mixed PDF extraction', () => {
  it('reads raster body despite a long embedded header and preserves real page mapping', async () => {
    const result = await extractDocument(await mixedPDF(), new AbortController().signal, () => {});
    expect(result.incomplete, result.warnings.join('\n')).toBe(false);
    expect(result.pageCount).toBe(2);
    expect(result.pageTexts).toHaveLength(2);
    expect(result.pageTexts[0]).toContain('Received 2026-09-12');
    expect(result.pageTexts[0]).toContain('100 mg');
    expect(result.pageTexts[0]).toContain('No fracture seen');
    expect(result.pageTexts[1]).toContain('Second page embedded source');
    expect(state.recognize).toHaveBeenCalledTimes(1);
    expect(result.usedOCR).toBe(true);
    expect(result.warnings.join(' ')).toContain('review the complete original page');
    expect(result.warnings.join(' ')).toContain('OCR');
  });
  it('marks failed image inspection incomplete while retaining embedded and OCR source text', async () => {
    state.failInspection = true;
    const result = await extractDocument(await mixedPDF(), new AbortController().signal, () => {});
    expect(result.incomplete).toBe(true);
    expect(result.pageTexts[0]).toContain('Received 2026-09-12');
    expect(result.pageTexts[0]).toContain('100 mg');
    expect(state.recognize).toHaveBeenCalledTimes(1);
    expect(result.warnings.join(' ')).toContain('Graphic content could not be inspected');
  });
  it('retains embedded source wording with explicit review when OCR fails', async () => {
    state.failOCR = true;
    const result = await extractDocument(await mixedPDF(), new AbortController().signal, () => {});
    expect(result.pageTexts[0]).toContain('Received 2026-09-12');
    expect(result.pageTexts[1]).toContain('Second page embedded source');
    expect(result.incomplete).toBe(true);
    expect(result.warnings.join(' ')).toContain('Embedded text was retained');
  });
  it('bounds mixed-page OCR at ten pages and retains page eleven for review', async () => {
    state.pages = 11;
    const result = await extractDocument(await mixedPDF(), new AbortController().signal, () => {});
    expect(state.recognize).toHaveBeenCalledTimes(10);
    expect(result.pageTexts).toHaveLength(11);
    expect(result.pageTexts[9]).toContain('100 mg');
    expect(result.pageTexts[10]).toContain('Received 2026-09-12');
    expect(result.pageTexts[10]).not.toContain('100 mg');
    expect(result.incomplete).toBe(true);
    expect(result.warnings.join(' ')).toContain('Page 11: Needs OCR beyond the 10-page OCR limit');
  });
});
