// Purpose: Ensure record detail never resurfaces legacy truncated local summaries as faithful source text.
// Inputs: Actual record detail rendering with synthetic current sources and old saved summaries.
// Outputs: Assertions for current complete-line previews, omissions, and retained AI/authored summaries.
// Side effects: Static React rendering and memory repository only; no browser storage or providers.
// @vitest-environment jsdom

import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';
import type { MedicalRecord } from '../../core/models';
import { RevaProvider } from '../../core/RevaContext';
import { RevaStore } from '../../core/store';
import { MemoryRepository, transport } from '../../core/__tests__/fixtures';
import { RecordDetail } from './RecordDetail';

async function renderRecord(values: Partial<MedicalRecord>) {
  const store = new RevaStore(new MemoryRepository(), () => transport());
  await store.initialize();
  await store.mutate((draft) => {
    Object.assign(
      draft.records[0],
      { isDemo: false, symptomEntry: undefined, summaryModel: undefined },
      values,
    );
  });
  return renderToStaticMarkup(
    <RevaProvider store={store}>
      <RecordDetail id={store.getState().snapshot!.records[0].id} />
    </RevaProvider>,
  );
}

// MARK: - Existing summaries cannot bypass complete-source preview boundaries
describe('record detail source previews', () => {
  it('renders current complete source lines instead of the persisted partial local summary', async () => {
    const html = await renderRecord({
      text: 'Exact source line with complete dose: 12.5 mg.',
      summary: 'Legacy clipped dose: 12.',
    });
    expect(html).toContain('Exact source line with complete dose: 12.5 mg.');
    expect(html).not.toContain('Legacy clipped dose');
  });

  it('directs the user to a readable long source instead of claiming text is missing', async () => {
    const html = await renderRecord({
      text: 'Long unbroken source wording '.repeat(100),
      summary: 'Legacy partial excerpt.',
    });
    expect(html).toContain('No complete source line fits this preview.');
    expect(html).not.toContain('No readable text yet');
    expect(html).not.toContain('Legacy partial excerpt.');
    expect(html).toContain('Full source text');
  });

  it('retains an explicitly attributed AI summary', async () => {
    const html = await renderRecord({
      text: 'Exact source wording.',
      summary: 'Separate mock AI overview.',
      summaryModel: 'mock-model',
    });
    expect(html).toContain('Separate mock AI overview.');
    expect(html).toContain('Generated by mock-model');
  });
});
