// Purpose: Preserve native record-version, transcript-memory and booking invariants.
// Inputs: Snapshot drafts and user-reviewed source/booking values.
// Outputs: Updated in-memory draft values or validation errors.
// Side effects: Mutates only supplied drafts; never persists or calls providers.
import type { AppSnapshot, BookingRequest, MedicalRecord, VisitRecording } from './models';
import { durationLabel, localExcerpt, nowISO, validZone } from './domain';

// MARK: - Source-aware version increments and optimistic record editing.
export function upsertRecord(snapshot: AppSnapshot, incoming: MedicalRecord, expectedVersion?: number): void {
  const index = snapshot.records.findIndex((record) => record.id === incoming.id),
    current = snapshot.records[index];
  if (expectedVersion !== undefined && (!current || current.version !== expectedVersion))
    throw new Error('This record changed or was deleted while you were editing. Reopen it before saving.');
  const revised = structuredClone(incoming);
  if (current) {
    const fields = ['title', 'date', 'text', 'tags', 'summary', 'status'] as const;
    revised.version =
      current.version +
      (fields.some((field) => JSON.stringify(current[field]) !== JSON.stringify(revised[field])) ? 1 : 0);
    snapshot.records[index] = revised;
  } else {
    revised.version = Math.max(1, revised.version);
    snapshot.records.push(revised);
  }
}

// MARK: - Transcript memory preserves stable IDs, original text and separate notes.
export function createMemoryRecord(
  recording: VisitRecording,
  snapshot: AppSnapshot,
  preserveNotes = false,
): MedicalRecord {
  const existing =
    snapshot.records.find((record) => record.id === `memory-${recording.id}`) ??
    snapshot.records.find((record) => record.sourceRecordingID === recording.id);
  const full = recording.segments
    .map(
      (segment) =>
        `[${durationLabel(segment.start)}–${durationLabel(segment.end)}] ${segment.speaker}: ${segment.text}`,
    )
    .join('\n\n');
  const text = full || recording.summary;
  if (!text.trim()) throw new Error('Add notes or a transcript before saving a visit memory.');
  const summary = localExcerpt(text),
    origin = recording.isSample
      ? 'Fictional sample transcript. No matching audio.'
      : recording.transcriptionModel
        ? `Transcript generated by ${recording.transcriptionModel}; review for accuracy.`
        : 'Saved visit memory from user-entered notes.';
  return {
    ...(existing ?? {
      id: `memory-${recording.id}`,
      title: `${recording.title} · memory`,
      kind: 'Recording',
      provider: snapshot.visits.find((visit) => visit.id === recording.visitID)?.provider ?? 'Visit',
      date: recording.createdAt.slice(0, 10),
      uploadedAt: nowISO(),
      tags: ['visit memory'],
      status: 'ready',
      pageCount: 1,
      notes: '',
      version: 1,
    }),
    text,
    summary,
    summaryModel: undefined,
    sourceRecordingID: recording.id,
    isDemo: recording.isSample,
    pageTexts: undefined,
    notes:
      preserveNotes && existing
        ? existing.notes
        : origin +
          (recording.summary
            ? `\n\nSeparate visit notes (not automatically changed with transcript corrections):\n${recording.summary}`
            : ''),
    version: existing
      ? existing.version + (existing.text !== text || existing.summary !== summary ? 1 : 0)
      : 1,
  };
}
export function reconcileMemory(snapshot: AppSnapshot, id: string, corrected?: Record<string, string>): void {
  const recording = snapshot.recordings.find((item) => item.id === id);
  if (!recording) throw new Error('This recording is no longer available.');
  const existing = snapshot.records.find(
    (record) => record.id === `memory-${id}` || record.sourceRecordingID === id,
  );
  if (corrected) {
    const ids = recording.segments.map((segment) => segment.id);
    if (
      !ids.length ||
      new Set(ids).size !== ids.length ||
      Object.keys(corrected).length !== ids.length ||
      ids.some((key) => !Object.hasOwn(corrected, key))
    )
      throw new Error('The source transcript changed. Reopen the correction editor.');
    const values = Object.values(corrected);
    if (
      values.some((text) => !text.trim() || text.length > 20_000) ||
      values.reduce((total, text) => total + text.length, 0) > 200_000
    )
      throw new Error('Keep segment text nonempty and under the transcript size limits.');
    recording.segments.forEach((segment) => {
      segment.text = corrected[segment.id];
    });
    if (!existing) return;
  }
  const memory = createMemoryRecord(recording, snapshot, !!corrected);
  const index = snapshot.records.findIndex((record) => record.id === memory.id);
  if (index < 0) snapshot.records.push(memory);
  else snapshot.records[index] = memory;
}

// MARK: - Local simulation validation and idempotent appointment confirmation.
export function validateBooking(request: BookingRequest): void {
  if (!request.clinic.trim() || request.phone.replace(/\D/g, '').length < 10 || !request.reason.trim())
    throw new Error('Enter a clinic, complete phone number, and visit reason.');
  if (
    !Number.isFinite(Date.parse(request.earliest)) ||
    !Number.isFinite(Date.parse(request.latest)) ||
    Date.parse(request.earliest) > Date.parse(request.latest) ||
    !validZone(request.timeZone)
  )
    throw new Error('Check the booking date range and time zone.');
}
export function confirmBooking(id: string, snapshot: AppSnapshot): void {
  const request = snapshot.bookings.find((item) => item.id === id);
  if (!request) throw new Error('Booking not found.');
  if (request.confirmedVisitID) return;
  const visit = snapshot.visits.find((item) => item.id === request.visitID);
  if (request.isLive || request.status !== 'proposed' || !visit)
    throw new Error('This simulated booking is not ready to confirm.');
  visit.date = request.earliest;
  visit.clinic = request.clinic;
  visit.timeZone = request.timeZone;
  request.status = 'confirmed';
  request.confirmedVisitID = visit.id;
}
