// Purpose: Preserve native record-version, transcript-memory and appointment-summary invariants.
// Inputs: Snapshot drafts and user-reviewed source and transcript values.
// Outputs: Updated in-memory draft values or validation errors.
// Side effects: Mutates only supplied drafts; never persists or calls providers.
import type { AppSnapshot, MedicalRecord, VisitRecording } from './models';
import { durationLabel, localExcerpt, nowISO } from './domain';
import { calendarDay } from './dates';
import { recordingInstant } from './recordingDates';

// MARK: - Source-aware version increments and optimistic record editing.
export function upsertRecord(snapshot: AppSnapshot, incoming: MedicalRecord, expectedVersion?: number): void {
  const index = snapshot.records.findIndex((record) => record.id === incoming.id),
    current = snapshot.records[index];
  if (expectedVersion !== undefined && (!current || current.version !== expectedVersion))
    throw new Error('This record changed or was deleted while you were editing. Reopen it before saving.');
  const revised = structuredClone(incoming);
  if (current) {
    if ((['title', 'text', 'date', 'dateSource'] as const).some((key) => current[key] !== revised[key])) {
      if (revised.summaryModel) revised.summary = localExcerpt(revised.text, revised.isDemo);
      revised.summaryModel = undefined;
      revised.summaryGeneratedAt = undefined;
    }
    const fields = ['title', 'date', 'dateSource', 'text', 'tags', 'summary', 'status'] as const;
    revised.version =
      current.version +
      (fields.some((field) => JSON.stringify(current[field]) !== JSON.stringify(revised[field])) ? 1 : 0);
    snapshot.records[index] = revised;
  } else {
    revised.version = Math.max(1, revised.version);
    snapshot.records.push(revised);
  }
}

// MARK: - Transcript memory preserves stable IDs, original text and separate notes.
export function recordingTranscript(recording: VisitRecording): string {
  return recording.segments
    .map(
      (segment) =>
        `[${durationLabel(segment.start)}–${durationLabel(segment.end)}] ${segment.speaker}: ${segment.text}`,
    )
    .join('\n\n');
}
export function hasRecordingSummary(recording: VisitRecording): boolean {
  return (
    recording.segments.length > 0 &&
    Boolean(
      recording.aiSummary?.trim() &&
      recording.aiSummaryModel?.trim() &&
      recording.aiSummaryGeneratedAt &&
      Number.isFinite(Date.parse(recording.aiSummaryGeneratedAt)),
    )
  );
}
export function clearRecordingSummary(recording: VisitRecording): void {
  recording.aiSummary = undefined;
  recording.aiSummaryModel = undefined;
  recording.aiSummaryGeneratedAt = undefined;
}
export function invalidateChangedRecordingSummaries(previous: AppSnapshot, draft: AppSnapshot): void {
  for (const recording of draft.recordings) {
    const before = previous.recordings.find((item) => item.id === recording.id);
    if (!before || JSON.stringify(before.segments) === JSON.stringify(recording.segments)) continue;
    clearRecordingSummary(recording);
    const index = draft.records.findIndex(
      (record) => record.id === `memory-${recording.id}` || record.sourceRecordingID === recording.id,
    );
    if (index >= 0 && (recording.segments.length || recording.summary.trim()))
      draft.records[index] = createMemoryRecord(recording, draft, true);
  }
}
export function createMemoryRecord(
  recording: VisitRecording,
  snapshot: AppSnapshot,
  preserveNotes = false,
): MedicalRecord {
  const existing =
    snapshot.records.find((record) => record.id === `memory-${recording.id}`) ??
    snapshot.records.find((record) => record.sourceRecordingID === recording.id);
  const full = recordingTranscript(recording);
  const text = full || recording.summary;
  if (!text.trim()) throw new Error('Add notes or a transcript before saving a visit memory.');
  const generated = hasRecordingSummary(recording) ? recording.aiSummary! : undefined;
  const summary = generated ?? localExcerpt(text),
    origin = recording.isSample
      ? 'Fictional sample transcript. No matching audio.'
      : recording.transcriptionModel
        ? `Transcript generated by ${recording.transcriptionModel}; review for accuracy.`
        : 'Saved visit memory from user-entered notes.';
  return {
    ...(existing ?? {
      id: `memory-${recording.id}`,
      title: `${recording.title} · memory`,
      kind: 'Recording',
      provider: snapshot.visits.find((visit) => visit.id === recording.visitID)?.provider ?? 'Visit',
      date: calendarDay(new Date(recordingInstant(recording))),
      dateSource: recording.capturedAt ? 'recorded' : recording.savedAt ? 'added' : undefined,
      uploadedAt: nowISO(),
      tags: ['visit memory'],
      status: 'ready',
      pageCount: 1,
      notes: '',
      version: 1,
    }),
    text,
    summary,
    summaryModel: generated ? recording.aiSummaryModel : undefined,
    summaryGeneratedAt: generated ? recording.aiSummaryGeneratedAt : undefined,
    sourceRecordingID: recording.id,
    isDemo: recording.isSample,
    pageTexts: undefined,
    notes:
      preserveNotes && existing
        ? existing.notes
        : origin +
          (recording.summary
            ? `\n\nSeparate visit notes (not automatically changed with transcript corrections):\n${recording.summary}`
            : ''),
    version: existing
      ? existing.version + (existing.text !== text || existing.summary !== summary ? 1 : 0)
      : 1,
  };
}
export function reconcileMemory(snapshot: AppSnapshot, id: string, corrected?: Record<string, string>): void {
  const recording = snapshot.recordings.find((item) => item.id === id);
  if (!recording) throw new Error('This recording is no longer available.');
  const existing = snapshot.records.find(
    (record) => record.id === `memory-${id}` || record.sourceRecordingID === id,
  );
  if (corrected) {
    const ids = recording.segments.map((segment) => segment.id);
    if (
      !ids.length ||
      new Set(ids).size !== ids.length ||
      Object.keys(corrected).length !== ids.length ||
      ids.some((key) => !Object.hasOwn(corrected, key))
    )
      throw new Error('The source transcript changed. Reopen the correction editor.');
    const values = Object.values(corrected);
    if (
      values.some((text) => !text.trim() || text.length > 20_000) ||
      values.reduce((total, text) => total + text.length, 0) > 200_000
    )
      throw new Error('Keep segment text nonempty and under the transcript size limits.');
    const changed = recording.segments.some((segment) => segment.text !== corrected[segment.id]);
    recording.segments.forEach((segment) => {
      segment.text = corrected[segment.id];
    });
    if (changed) clearRecordingSummary(recording);
    if (!existing) return;
  }
  const memory = createMemoryRecord(recording, snapshot, !!corrected);
  const index = snapshot.records.findIndex((record) => record.id === memory.id);
  if (index < 0) snapshot.records.push(memory);
  else snapshot.records[index] = memory;
}
