// Purpose: Read a saved source, its summary, and linked original or transcript.
// Inputs: Record ID, optional source page, and AppStore.
// Outputs: Source details, review actions, and linked source previews.
// Side effects: Can request AI summarization or delete a record through AppStore.

import SwiftUI

// MARK: - RecordDetailView
/// Read a saved source, its summary, and linked original or transcript.
struct RecordDetailView: View {
    // MARK: - Inputs and view state

    @EnvironmentObject private var store: AppStore
    @Environment(\.dismiss) private var dismiss
    let id: String
    var sourcePage: Int = 1
    @State private var editing = false
    @State private var deleting = false
    @State private var original = false
    // MARK: - Rendering and navigation
    var body: some View {
        Group {
            if let record = store.record(id) {
                Page {
                    HStack {
                        IconTile(symbol: record.symbol)
                        Spacer()
                        ModeBadge(text: record.isDemo ? "SYNTHETIC RECORD" : "SAVED ON DEVICE")
                    }
                    Text(record.title).font(.title.bold())
                    if record.symptomEntry == nil {
                        DetailLine(symbol: "calendar", text: RevaDate.display(record.date))
                    }
                    DetailLine(
                        symbol: record.symptomEntry == nil ? "building.2" : "person", text: record.provider)
                    if record.needsReview {
                        StatusNotice(
                            title: "Review the source",
                            message:
                                "Some text or dates need confirmation. Compare the original before using this record in a visit.",
                            symbol: "exclamationmark.circle")
                    }
                    if let entry = record.symptomEntry {
                        SymptomEntryDetailsView(entry: entry)
                    }
                    if record.symptomEntry == nil || record.summaryModel != nil {
                        RevaCard {
                            Label(
                                record.summaryModel != nil || hasAuthoredSummary(record)
                                    ? record.summaryLabel : "Local excerpt", systemImage: "text.alignleft"
                            ).font(.headline).foregroundStyle(RevaTheme.accent)
                            Text(
                                displayedSummary(record).isEmpty
                                    ? "No complete source line fits in this excerpt. Open the source to review its text."
                                    : displayedSummary(record)
                            ).font(.body).textSelection(.enabled)
                            if record.summaryModel == nil && !hasAuthoredSummary(record)
                                && ReportEngine.localExcerptDetails(record.text, isDemo: record.isDemo)
                                    .omitted
                            {
                                Text(ReportEngine.omissionNotice).font(.caption).foregroundStyle(.secondary)
                            }
                            Text(
                                record.summaryModel != nil
                                    ? "Generated by the connected AI service. Check details against the original source."
                                    : hasAuthoredSummary(record)
                                        ? "Prepared from fictional source material for this demo."
                                        : "An automatic excerpt of extracted text created on this device."
                            ).font(.caption).foregroundStyle(.secondary)
                        }
                    }
                    if store.useConnectedAI {
                        Button(
                            store.isProviderBusy ? "Working with connected service…" : "Summarize with Gemini"
                        ) { Task { await store.summarizeWithAI(record.id) } }.buttonStyle(.bordered).disabled(
                            store.isProviderBusy || record.text.isEmpty)
                    }
                    if store.sourceURL(record) != nil {
                        Button {
                            original = true
                        } label: {
                            Label(
                                sourcePage > 0 ? "Open original · page \(sourcePage)" : "Open original",
                                systemImage: "doc.richtext")
                        }.buttonStyle(.bordered).controlSize(.large).frame(maxWidth: .infinity)
                    }
                    if let recordingID = record.sourceRecordingID {
                        if store.recording(recordingID) != nil {
                            NavigationLink {
                                RecordingDetailView(id: recordingID)
                            } label: {
                                Label("Open visit transcript", systemImage: "text.bubble")
                            }.buttonStyle(.bordered).controlSize(.large).frame(maxWidth: .infinity)
                        } else {
                            StatusNotice(
                                title: "Source transcript unavailable",
                                message:
                                    "The originating recording was deleted or is no longer available. This saved memory retains its text.",
                                symbol: "text.bubble")
                        }
                    }
                    if !record.notes.isEmpty {
                        RevaCard {
                            Text("Notes").font(.headline)
                            Text(record.notes).textSelection(.enabled)
                        }
                    }
                    if record.symptomEntry == nil {
                        RevaCard {
                            DisclosureGroup("Full extracted text") {
                                Text(
                                    record.text.isEmpty
                                        ? "No text extracted. Add a correction using Edit." : record.text
                                ).font(.subheadline).textSelection(.enabled).padding(.top, 10)
                            }
                        }
                    }
                    Button(record.symptomEntry == nil ? "Edit record & review text" : "Edit symptom entry") {
                        editing = true
                    }.buttonStyle(PrimaryButtonStyle())
                    Button(
                        record.symptomEntry == nil ? "Delete record" : "Delete symptom entry",
                        role: .destructive
                    ) { deleting = true }.frame(maxWidth: .infinity).padding(.top, 5)
                }
                .sheet(isPresented: $editing) {
                    NavigationStack {
                        if record.symptomEntry != nil {
                            SymptomEntryEditorView(record: record)
                        } else {
                            RecordEditorView(record: record)
                        }
                    }
                }
                .sheet(isPresented: $original) {
                    if let url = store.sourceURL(record) {
                        SourcePreview(url: url, page: sourcePage, title: record.title)
                    }
                }
            } else {
                ContentUnavailableView(
                    "Source no longer available", systemImage: "doc.questionmark",
                    description: Text(
                        "This record was deleted. Regenerate the visit brief to update its evidence."))
            }
        }.navigationTitle(store.record(id)?.symptomEntry == nil ? "Record" : "User symptom entry")
            .navigationBarTitleDisplayMode(.inline)
            .confirmationDialog(
                "Delete this record from your local history? Existing briefs will be marked out of date.",
                isPresented: $deleting, titleVisibility: .visible
            ) {
                Button("Delete record", role: .destructive) {
                    if store.perform({ try store.deleteRecord(id) }) { dismiss() }
                }
            }
    }
    // MARK: - Summary provenance
    /// A fictional record keeps its origin badge after a text correction, but its authored demo summary is replaced by a local excerpt; label what is shown.
    private func displayedSummary(_ record: MedicalRecord) -> String {
        record.summaryModel != nil || hasAuthoredSummary(record)
            ? record.summary : ReportEngine.localExcerpt(record.text, isDemo: record.isDemo)
    }
    private func hasAuthoredSummary(_ record: MedicalRecord) -> Bool {
        ReportEngine.hasAuthoredDemoSummary(record)
    }
}
